Recommendations Block: Handle failed HTTP request
When the Parse.ly Recommendations API was not accessible to the proxy endpoint, such as when developing offline or if the Parse.ly API was down, and recommendations were not able to be retrieved, then the block editor displayed:

> Error: {"errors":{"http_request_failed":["A valid URL was not provided."]},"error_data":[]}

The error message comes from WP_HTTP class in WordPress core, and in this case was slightly misleading, as the attempted URL was correct.

By adding some `errorMesssage` handling to the block's JavaScript, we can improve the message and avoid JSON being shown, so it reads as:

> The Parse.ly Recommendations API is not accessible. You may be offline.