Add filter wp_parsely_post_type for NewsArticle (#270)
* Add filter for NewsArticle

* Add tests for the new wp_parsely_post_type filter

* Address the failed test in PHP 5.6.

Ref: https://github.com/Parsely/wp-parsely/runs/2489611164

---

There was 1 error:

1) Parsely\Tests\All_Test::test_filter_wp_parsely_post_type
ReflectionException: Class PHPUnit\Framework\Error\Warning does not exist

* Fix the wrong paths for `views` files

Seems a regression of #262

* Apply cosmetic changes from Gary's review

Co-authored-by: Gary Jones <gary.jones@automattic.com>

* Update method convert_jsonld_to_parsely_type

* Update class-all-test.php after running PHPCBF

* Address "Undefined index: logo" when running tests

Detailed error:

1) Parsely\Tests\All_Test::test_filter_wp_parsely_post_type
Undefined index: logo

/src/class-parsely.php:1011
/tests/class-all-test.php:993

* Add extra info for test_filter_wp_parsely_post_type

* Apply suggestions from code review by Gary

Co-authored-by: Gary Jones <gary.jones@automattic.com>

* Updated wording from `allowed` to `supported`

Ref https://github.com/Parsely/wp-parsely/pull/270/files#r626379194

Co-authored-by: Gary Jones <gary.jones@automattic.com>
Co-authored-by: Jeff Bowen <jblz@users.noreply.github.com>