Address the failed test in PHP 5.6.
Ref: https://github.com/Parsely/wp-parsely/runs/2489611164

---

There was 1 error:

1) Parsely\Tests\All_Test::test_filter_wp_parsely_post_type
ReflectionException: Class PHPUnit\Framework\Error\Warning does not exist